pChart_index: 
    pattern:  /index
    defaults: { _controller: pChartBundle:Examples:index }

pChart_view: 
    pattern:  /view/{number}
    defaults: { _controller: pChartBundle:Examples:view }

pChart_example: 
    pattern:  /example/{number}
    defaults: { _controller: pChartBundle:Examples:example }
